##jobname
```{r}
jobname<-"PRL_V2_1.2recluster"
```

##packages
```{r}
library(dplyr)
library(Seurat)
library(patchwork)
library(readr)
library(cols4all)
library(openxlsx)
library(tibble)
library(SeuratData)
library(SeuratWrappers)
library(patchwork)
library(tidyverse)
library(loupeR)
```

##
```{r}
levels(sobj$class)
celltypes<-levels(sobj$class)[1:5]
```


##subset function
```{r}
recluster<-function(x){
  sobj.subset<-subset(sobj,subset = class==x)
  integration_method<-FastMNNIntegration

# Read the Seurat object
# sobj.subset <- readRDS("../../2024-03-06_27-integrate-harmony/data/sobj.subset_PD_before_integrate.rds")
  sobj.subset@assays$RNA@layers$data<-NULL
  sobj.subset[["RNA"]]<-split(sobj.subset[["RNA"]], f = sobj.subset$orig.ident)
  
  sobj.subset <- NormalizeData(sobj.subset)
  sobj.subset <- FindVariableFeatures(sobj.subset)
  sobj.subset <- ScaleData(sobj.subset)
  sobj.subset <- RunPCA(sobj.subset)
  
  # Perform integration dynamically
  sobj.subset <- IntegrateLayers(
    object = sobj.subset, method = integration_method,
    new.reduction = reduction_name,
    verbose = TRUE)
  
  # Re-join layers after integration
  sobj.subset[["RNA"]] <- JoinLayers(sobj.subset[["RNA"]])
  
  sobj.subset <- FindNeighbors(sobj.subset, reduction = reduction_name, dims = 1:15)
  sobj.subset <- FindClusters(sobj.subset, resolution = seq(0.1, 1, 0.1))
  sobj.subset <- RunUMAP(sobj.subset, dims = 1:15, reduction = reduction_name)
  
  return(sobj.subset)
}


```


```{r}
for (i in celltypes) {
  sobj.subset<-recluster(i)
  
  
  
  outRDS <- paste0("../Documents/sobj_PD_",i, identifier, ".rds")
  outPDF_QC <- paste0("../plots/sobjPD_",i, identifier, "_QC.pdf")
  outPDF <- paste0("../plots/sobj_PD_", i,identifier, ".pdf")
  outLoupe <- paste0("../Documents/louper_PD_",i, identifier)

  plot <- DimPlot(sobj.astro, reduction = "umap", group.by = "RNA_snn_res.0.5")
  ggsave(outPDF, plot, width = 7, height = 7, units = "in")
  
  saveRDS(sobj.subset, file = outRDS)
  
  cellnumber<-data.frame(cluster=levels(sobj$RNA_snn_res.0.5)) %>% arrange %>%
  mutate(class="",subclass="",subcluster="")
  write_csv(cellnumber,paste0("Documents/",i,"_cellnumber.csv"))
  
  
}
```


```{r}

# Save plots
# plot <- DimPlot(sobj.subset, reduction = "umap", split.by = "orig.ident")
# ggsave(outPDF_QC, plot, width = 7, height = 7, units = "in")

plot <- DimPlot(sobj.astro, reduction = "umap", group.by = "RNA_snn_res.0.5")
ggsave(outPDF, plot, width = 7, height = 7, units = "in")

create_loupe_from_seurat(sobj.astro, output_name = outLoupe)

# Save the integrated Seurat object
saveRDS(sobj.subset, file = outRDS)
```


##Export clusters
```{r}
# dir.create("Documents")
cellnumber<-data.frame(cluster=levels(sobj$RNA_snn_res.0.5)) %>% arrange %>%
  mutate(class="",subclass="",subcluster="")
write_csv(cellnumber,"Documents/cellnumber.csv")
```

###Export marker
```{r QC,analysis}
varuse<-"RNA_snn_res.0.5"
Idents(sobj)<-varuse
sobj.Markers<-FindAllMarkers(sobj,only.pos = TRUE, min.pct = 0.25, logfc.threshold = 0.25)
sobj.Markers %>%
  group_by(cluster) %>%
  top_n(n = 30, wt = avg_log2FC) -> top30

write.xlsx(top30, file = paste0("Documents/",varuse,"_Top30.xlsx"))
write.xlsx(sobj.Markers, file = paste0("Documents/",varuse,".xlsx"))


```
