##job name
```{r}
jobname<-"PRLV2_13"
plot_path<-"../plots/"
Document_path<-"../Documents/"
```

```{r}
dir.create(plot_path)
dir.create(Document_path)
```
##packages
```{r}
library(dplyr)
library(Seurat)
library(patchwork)
library(readr)
library(cols4all)
library(openxlsx)
library(tibble)
library(SeuratData)
library(SeuratWrappers)
library(patchwork)
library(tidyverse)
library(loupeR)
```
##load data
```{r}
sobj<-readRDS("/storage/liuxiaodongLab/fanyi/FY/PRL_V2/20250102-12-Annotation-DropDoublets/Documents/PD_MNN_afterfilter.rds")
```

##Intergrate
FastMNNIntegration
```{r}

# Integration method and identifier
# integration_method <- args[1]
integration_method<-FastMNNIntegration
# identifier <- args[2]
identifier<-"MNN"
# Print the parameters
# cat("Integration Method:", integration_method, "\n")
cat("Identifier:", identifier, "\n")

# Construct the name for the new reduction
reduction_name <- paste('integrated', identifier, sep = '.')

# Print the new reduction name
cat("Reduction Name:", reduction_name, "\n")

# File paths
outRDS <- paste0("../Documents/sobj_PD_", identifier, ".rds")
outPDF_QC <- paste0("../plots/sobj_PD_", identifier, "_QC.pdf")
outPDF <- paste0("../plots/sobj_PD_", identifier, ".pdf")
outLoupe <- paste0("../Documents/louper_PD_", identifier)

# Print file paths
cat("Output RDS File:", outRDS, "\n")
cat("Output QC PDF File:", outPDF_QC, "\n")
cat("Output PDF File:", outPDF, "\n")
cat("Output Loupe File:", outLoupe, "\n")

# Read the Seurat object
# sobj <- readRDS("../../2024-03-06_27-integrate-harmony/data/sobj_PD_before_integrate.rds")
sobj[["RNA"]]<-split(sobj[["RNA"]], f = sobj$orig.ident)

sobj <- NormalizeData(sobj)
sobj <- FindVariableFeatures(sobj)
sobj <- ScaleData(sobj)
sobj <- RunPCA(sobj)

# Perform integration dynamically
sobj <- IntegrateLayers(
  object = sobj, method = integration_method,
  new.reduction = reduction_name,
  verbose = TRUE)

# Re-join layers after integration
sobj[["RNA"]] <- JoinLayers(sobj[["RNA"]])

# Further analysis steps
sobj <- FindNeighbors(sobj, reduction = reduction_name, dims = 1:30)
sobj <- FindClusters(sobj, resolution = seq(0.1, 1, 0.1))
sobj <- RunUMAP(sobj, dims = 1:30, reduction = reduction_name)

# Save plots
# plot <- DimPlot(sobj, reduction = "umap", split.by = "sample")
# ggsave(outPDF_QC, plot, width = 7, height = 7, units = "in")

plot <- DimPlot(sobj, reduction = "umap", group.by = "RNA_snn_res.0.5")
ggsave(outPDF, plot, width = 7, height = 7, units = "in")

create_loupe_from_seurat(sobj, output_name = outLoupe)

# Save the integrated Seurat object
saveRDS(sobj, file = outRDS)
```

```{r}
Idents(sobj)<-"class"
DimPlot(sobj)
```


